"""Polymarket CLOB integration — client, orders, WebSocket, contracts, data, signing, metrics, errors."""

from polymind.polymarket.client import PolymarketClient
from polymind.polymarket.contracts import (
    ContractsConfig,
    ContractsGateway,
    MergeResult,
    OnChainBalance,
    RedeemResult,
    SplitResult,
    TokenBalance,
    TransactionResult,
)
from polymind.polymarket.data_api import (
    Candle,
    DataAPIConfig,
    MarketDetail,
    OrderbookSnapshot,
    OrderLevel,
    PolymarketDataAPI,
    Trade,
    VolumeInfo,
)
from polymind.polymarket.errors import (
    AuthenticationError,
    ConnectionError,
    ContractError,
    InsufficientAuthError,
    InsufficientGasError,
    MarketNotFoundError,
    NonceTooLowError,
    OrderRejectedError,
    PolymarketError,
    RateLimitError,
)
from polymind.polymarket.metrics import AdapterMetrics, Counter, Histogram, MetricsSummary
from polymind.polymarket.signer import (
    ApiKeyCredentials,
    AuthTier,
    Signer,
    WalletCredentials,
)
from polymind.polymarket.websocket import (
    MarketEvent,
    PolymarketWebSocketAdapter,
    WebSocketChannel,
    WebSocketConfig,
)

__all__ = [
    "PolymarketClient",
    "PolymarketWebSocketAdapter",
    "WebSocketConfig",
    "WebSocketChannel",
    "MarketEvent",
    "PolymarketDataAPI",
    "DataAPIConfig",
    "MarketDetail",
    "OrderbookSnapshot",
    "OrderLevel",
    "Candle",
    "Trade",
    "VolumeInfo",
    "ContractsGateway",
    "ContractsConfig",
    "OnChainBalance",
    "SplitResult",
    "MergeResult",
    "RedeemResult",
    "TokenBalance",
    "TransactionResult",
    "Signer",
    "AuthTier",
    "ApiKeyCredentials",
    "WalletCredentials",
    "AdapterMetrics",
    "Counter",
    "Histogram",
    "MetricsSummary",
    "AuthenticationError",
    "ConnectionError",
    "ContractError",
    "InsufficientAuthError",
    "InsufficientGasError",
    "MarketNotFoundError",
    "NonceTooLowError",
    "OrderRejectedError",
    "PolymarketError",
    "RateLimitError",
]
